name: 3ds-release

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:

  build-3ds-release:
    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm:latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git build-essential cmake zip

      - name: Configure
        run: |
          cd $GITHUB_WORKSPACE
          source /etc/profile.d/devkit-env.sh
          mkdir cmake-build && cd cmake-build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. \
            -DPLATFORM_3DS=ON -DOPTION_LIGHT=ON -DOPTION_MPV_PLAYER=OFF

      - name: Build pgen
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make pgen.3dsx
