name: linux-release

on:
  push:
    tags:
      - "v*.*"

jobs:

  build-linux-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install \
              git zip build-essential cmake xxd \
              liblzma-dev libsdl2-dev libconfig-dev libcurl4-openssl-dev libtinyxml2-dev \
              libconfig-dev libglm-dev libfreetype6-dev libpng-dev libminizip-dev zlib1g-dev \
              libvdpau-dev libva-dev libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev \
              libpostproc-dev libswresample-dev libswscale-dev libmpv-dev libass-dev libbz2-dev \
              libfribidi-dev libzip-dev libfuse-dev

      - name: Build pfbneo
        run: |
          mkdir cmake-build-pfbneo && cd cmake-build-pfbneo
          cmake -G "Unix Makefiles" -DPLATFORM_LINUX=ON -DOPTION_EMU=pfbneo -DCMAKE_BUILD_TYPE=Release ..
          make pfbneo.deps
          make -j $(getconf _NPROCESSORS_ONLN) pfbneo
          mv pfbneo/pfbneo $GITHUB_WORKSPACE/pfbneo-linux

      - name: Build pgen
        run: |
          mkdir cmake-build-pgen && cd cmake-build-pgen
          cmake -G "Unix Makefiles" -DPLATFORM_LINUX=ON -DOPTION_EMU=pgen -DCMAKE_BUILD_TYPE=Release ..
          make -j $(getconf _NPROCESSORS_ONLN) pgen
          mv pgen/pgen $GITHUB_WORKSPACE/pgen-linux

      - name: Build pnes
        run: |
          mkdir cmake-build-pnes && cd cmake-build-pnes
          cmake -G "Unix Makefiles" -DPLATFORM_LINUX=ON -DOPTION_EMU=pnes -DCMAKE_BUILD_TYPE=Release ..
          make -j $(getconf _NPROCESSORS_ONLN) pnes
          mv pnes/pnes $GITHUB_WORKSPACE/pnes-linux

      - name: Build psnes
        run: |
          mkdir cmake-build-psnes && cd cmake-build-psnes
          cmake -G "Unix Makefiles" -DPLATFORM_LINUX=ON -DOPTION_EMU=psnes -DCMAKE_BUILD_TYPE=Release ..
          make -j $(getconf _NPROCESSORS_ONLN) psnes
          mv psnes/psnes $GITHUB_WORKSPACE/psnes-linux

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $GITHUB_WORKSPACE/*-linux
          token: ${{ secrets.RELEASE_TOKEN }}
