name: pfbneo-windows-dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-pfbneo-windows-dev:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: '🧰 Checkout'
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        with:
          msystem: MINGW64
          update: true
          install: >-
            git zip perl make
            mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-cmake mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL2 mingw-w64-x86_64-freetype mingw-w64-x86_64-glm
            mingw-w64-x86_64-glew mingw-w64-x86_64-libconfig mingw-w64-x86_64-tinyxml2
            mingw-w64-x86_64-mpv mingw-w64-x86_64-zlib mingw-w64-x86_64-minizip
      - name: Build pfbneo
        run: |
          cmake -G "MSYS Makefiles" -DPLATFORM_WINDOWS=ON -DOPTION_EMU=pfbneo -DCMAKE_BUILD_TYPE=Debug ..
          make pfbneo.deps
          make -j pfbneo
