name: pfbneo-switch-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-pfbneo-switch-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git cmake zip

      # Build pfbneo
      - name: Build pfbneo
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          source /etc/profile.d/devkit-env.sh
          cmake -G "Unix Makefiles" -DPLATFORM_SWITCH=ON -DOPTION_EMU=pfbneo \
            -DCMAKE_BUILD_TYPE=Release ..
          make pfbneo.deps
          make -j $(getconf _NPROCESSORS_ONLN) pfbneo_switch_release
          
