name: pnes-ps4-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-pnes-ps4-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git build-essential cmake zip libgpgme11

      # Install dotnet sdk (for pkgtool)
      - name: Install dotnet sdk
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt -yq update
          sudo apt -yq install apt-transport-https
          sudo apt -yq update
          sudo apt-get install -yq dotnet-sdk-3.1

      # Install ps4 toolchain
      - name: Install ps4 toolchain
        run: |
          wget https://github.com/PacBrew/pacbrew-pacman/releases/download/pacbrew-release-1.0/pacbrew-pacman-1.0.deb
          sudo dpkg -i pacbrew-pacman-1.0.deb
          sudo pacbrew-pacman -Syu
          sudo pacbrew-pacman --noconfirm -S ps4-openorbis ps4-openorbis-portlibs

      # Build pnes
      - name: Build pnes
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          export OPENORBIS=/opt/pacbrew/ps4/openorbis
          cmake -G "Unix Makefiles" -DPLATFORM_PS4=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=pnes -DCMAKE_BUILD_TYPE=Debug ..
          make -j $(getconf _NPROCESSORS_ONLN) pnes_pkg
