name: psnes-linux-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-psnes-linux-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install \
              git zip build-essential cmake xxd \
              liblzma-dev libsdl2-dev libconfig-dev libcurl4-openssl-dev libtinyxml2-dev \
              libconfig-dev libglm-dev libfreetype6-dev libpng-dev libminizip-dev zlib1g-dev \
              libvdpau-dev libva-dev libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev \
              libpostproc-dev libswresample-dev libswscale-dev libmpv-dev libass-dev libbz2-dev \
              libfribidi-dev libzip-dev libfuse-dev

      # Build psnes
      - name: Build psnes
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          cmake -G "Unix Makefiles" -DPLATFORM_LINUX=ON -DOPTION_BUILTIN_LIBCONFIG=ON \
            -DOPTION_EMU=psnes -DCMAKE_BUILD_TYPE=Release ..
          make -j $(getconf _NPROCESSORS_ONLN) psnes_linux_release
          
