name: psnes-vita-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-psnes-vita-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install build dependencies
      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install build-essential cmake git zip curl python

      # Install vita toolchain
      - name: Install vita toolchain
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./install-all.sh

      # Build psnes
      - name: Build psnes
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          export VITASDK=/usr/local/vitasdk
          cmake -G "Unix Makefiles" -DPLATFORM_VITA=ON \
            -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=psnes -DCMAKE_BUILD_TYPE=Debug ..
          make -j $(getconf _NPROCESSORS_ONLN) psnes.vpk
