name: vita-dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:

  build-vita-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install build-essential cmake git zip curl python

      - name: Install vita toolchain
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./install-all.sh

      - name: Build pfbneo
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build-pfbneo && cd cmake-build-pfbneo
          export VITASDK=/usr/local/vitasdk
          cmake -G "Unix Makefiles" -DPLATFORM_VITA=ON \
            -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=pfbneo -DCMAKE_BUILD_TYPE=Debug ..
          make pfbneo.deps
          make -j $(getconf _NPROCESSORS_ONLN) pfbneo.vpk

      - name: Build pgen
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build-pgen && cd cmake-build-pgen
          export VITASDK=/usr/local/vitasdk
          cmake -G "Unix Makefiles" -DPLATFORM_VITA=ON \
            -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=pgen -DCMAKE_BUILD_TYPE=Debug ..
          make -j $(getconf _NPROCESSORS_ONLN) pgen.vpk

      - name: Build pnes
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build-pnes && cd cmake-build-pnes
          export VITASDK=/usr/local/vitasdk
          cmake -G "Unix Makefiles" -DPLATFORM_VITA=ON \
            -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=pnes -DCMAKE_BUILD_TYPE=Debug ..
          make -j $(getconf _NPROCESSORS_ONLN) pnes.vpk

      - name: Build psnes
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build-psnes && cd cmake-build-psnes
          export VITASDK=/usr/local/vitasdk
          cmake -G "Unix Makefiles" -DPLATFORM_VITA=ON \
            -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF \
            -DOPTION_EMU=psnes -DCMAKE_BUILD_TYPE=Debug ..
          make -j $(getconf _NPROCESSORS_ONLN) psnes.vpk