name: vita-dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:

  build-vita-dev:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install build-essential cmake git zip curl python

      - name: Install vita toolchain
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./install-all.sh

      - name: Configure
        run: |
          cd $GITHUB_WORKSPACE
          export VITASDK=/usr/local/vitasdk
          mkdir cmake-build && cd cmake-build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug .. \
            -DPLATFORM_VITA=ON -DOPTION_LIGHT=ON -DOPTION_BUILTIN_MINIZIP=ON -DOPTION_MPV_PLAYER=OFF

      - name: Build pfbneo
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make pfbneo.deps
          make pfbneo.vpk

      - name: Build pgen
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make pgen.vpk

      - name: Build pnes
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make pnes.vpk

      - name: Build psnes
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make psnes.vpk
